### ISSUE TITLE
Error: The 'R.string.auth_config' value it's not defined in your project's resources file

### ISSUE THREAD

**Issue by agfp** [nodriver-ai/flutter_azure_b2c#3]
When running the sample, I get the following error:

```
E/MethodChannel#flutter_azure_b2c(17481): java.lang.IllegalArgumentException: The 'R.string.auth_config' value it's not defined in your project's resources file.
E/MethodChannel#flutter_azure_b2c(17481): 	at com.nodriver.flutter_azure_b2c.PluginUtilities$Companion.getRawResourceIdentifier(Util.kt:69)
E/MethodChannel#flutter_azure_b2c(17481): 	at com.nodriver.flutter_azure_b2c.B2CProvider.init(B2CProvider.kt:73)
E/MethodChannel#flutter_azure_b2c(17481): 	at com.nodriver.flutter_azure_b2c.B2CPlugin.onMethodCall(B2CPlugin.kt:69)
E/MethodChannel#flutter_azure_b2c(17481): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_azure_b2c(17481): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_azure_b2c(17481): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter_azure_b2c(17481): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_azure_b2c(17481): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter_azure_b2c(17481): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter_azure_b2c(17481): 	at android.app.ActivityThread.main(ActivityThread.java:6942)
E/MethodChannel#flutter_azure_b2c(17481): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_azure_b2c(17481): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#flutter_azure_b2c(17481): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by chipscal** [comment]
Did you created such asset as indicated in the readme? There is a template file and you should fill it with your azure ad b2c information.

**Comment by mario-neb** [comment]
the file name inside raw folder in  /android/app/main/res/raw/ should be auth_config (auth_config.json)

**Comment by chipscal** [comment]
I assume the problem was solved due to inactivity.
